### ISSUE TITLE
Player .acc stream content

### ISSUE THREAD

**Issue by ChrisGi** [ferPrieto/HarmonyOS-Wearable-Kata#18]
Does ohos.media.player.Player supports a Content-type audio/aac

Example radio uri(https://streams.kqed.org/kqedradio) in entry/src/main/java/com/fprieto/wearable/presentation/ui/slice/AudioPlayerAbilitySlice.java is a Content-type audio/mpeg and works on Huawei Watch 3(2.0.0.0.187)

example audio/aac stream:
https://media-the.musicradio.com/ClassicFM

**Comment by ferPrieto** [comment]
Hey @ChrisGi,

Regarding that type of stream, you will need a different dependency that supports _audio/aac_. The first one you can find below only supports sound and the second one is a _OHOS_ version of **ExoPlayer** that supports video too:

- [https://gitee.com/oc_wind/audio-demo](Audio library)

- [https://gitee.com/ts_ohos/ExoPlayer](Video Exoplayer library)

**Comment by ferPrieto** [comment]
This issue will get **marked** as **solved in three days**, unless there's any other problem.
